=pod

=encoding utf8

=head2 jmp

Search files and jump to matching lines in a text editor

=for HTML <a href="https://travis-ci.org/nige123/jmp.nigelhamilton.com"><img src="https://travis-ci.org/nige123/jmp.nigelhamilton.com.svg?branch=master"></a>
    
=head1 Installation

=head4 Manual

    $ zef install jmp

=head1 USAGE

    jmp - search files and jump to matching lines in a text editor

    Usage:
    
        jmp config -- edit ~/.jmp config to set the editor and search commands 
        jmp edit <filename> [<line-number>] -- start editing at a line number
        jmp edit <filename> '[<search-terms> ...]' -- start editing at a matching line
        jmp find '[<search-terms> ...]' -- find search terms in files    


=cut
